### ISSUE TITLE
[bug] cant load

### ISSUE THREAD

**Issue by alexzanderr** [nvim-telescope/telescope-node-modules.nvim#2]
actions i did:
- installed with `use "nvim-telescope/telescope-node-modules.nvim"`
- installed `telescope`
- loaded extension with `require'telescope'.load_extension'node_modules'` (after telescope setup)
- telescope is working fine

it says it could load the extensions because it doesnt exist. maybe name is wrong?

**Comment by delphinus** [comment]
Hi, I fixed several errors I've seen with the latest telescope. Can you try again?

**Comment by alexzanderr** [comment]
this explains a lot.

https://user-images.githubusercontent.com/54772464/136698376-895c5847-4389-47dc-bc6a-623ea0d3104a.mp4

**Comment by alexzanderr** [comment]
my bad. its working now.
https://user-images.githubusercontent.com/54772464/136698453-cef21c6e-713a-43c0-a658-d3dccb27cebd.mp4

**Comment by delphinus** [comment]
It's good! And sorry for my late reply 😉
